class BashFormatTput:
    bold = "$(tput bold)"
    normal = "$(tput sgr0)"


class FBash:
    __S__ = "\\033["
    __E__ = "m"
    NORMAL = f"{__S__}0{__E__}"
    BOLD = f"{__S__}1{__E__}"
    DIM = f"{__S__}2{__E__}"
    ITALIC = f"{__S__}3{__E__}"
    UNDERLINED = f"{__S__}4{__E__}"
    BLINKING = f"{__S__}5{__E__}"
    REVERSE = f"{__S__}7{__E__}"
    INVISIBLE = f"{__S__}8{__E__}"
    BLACK = f"{__S__}0;30{__E__}"
    RED = f"{__S__}0;31{__E__}"
    GREEN = f"{__S__}0;32{__E__}"
    BROWN = f"{__S__}0;33{__E__}"
    BLUE = f"{__S__}0;34{__E__}"
    PURPLE = f"{__S__}0;35{__E__}"
    CYAN = f"{__S__}0;36{__E__}"
    LIGHT_GRAY = f"{__S__}0;37{__E__}"
    DARK_GRAY = f"{__S__}1;30{__E__}"
    LIGHT_RED = f"{__S__}1;31{__E__}"
    LIGHT_GREEN = f"{__S__}1;32{__E__}"
    YELLOW = f"{__S__}1;33{__E__}"
    LIGHT_BLUE = f"{__S__}1;34{__E__}"
    LIGHT_PURPLE = f"{__S__}1;35{__E__}"
    LIGHT_CYAN = f"{__S__}1;36{__E__}"
    WHITE = f"{__S__}1;37{__E__}"
